import './globals.css';
import React from 'react';
import Navbar from '@/components/Navbar/Navbar';
import Footer from '@/components/Footer/Footer';
import { AuthProvider } from '@/context/AuthContext';
import { CartProvider } from '@/context/CartContext';
import { OrderProvider } from '@/context/OrderContext';
import { UserProvider } from '@/context/UserContext';

export const metadata = {
   title: 'ClickNest',
   description: 'Generated by Next.js',
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en">
         <head>
            <link rel="icon" href="/raven.svg" type="image/svg+xml" />
         </head>
         <body className="overscroll-none">
            <AuthProvider>
               <UserProvider>
                  <CartProvider>
                     <OrderProvider>
                        <Navbar></Navbar>
                        <div className="min-h-screen">{children}</div>
                        <Footer></Footer>
                     </OrderProvider>
                  </CartProvider>
               </UserProvider>
            </AuthProvider>
         </body>
      </html>
   );
}
